"""Data quality: rules, the engine that runs them, scoring, and measurement against planted faults."""

from .context import SeriesContext
from .engine import QualityEngine, QualityReport, SeriesScore, fx_series_rules, run_quality, series_report
from .evaluation import EXPECTED_RULES, DetectionScore, KindScore, RuleScore, evaluate
from .findings import DIMENSION_WEIGHTS, Dimension, Finding, Severity
from .fx_rules import FxInverseRule, FxTriangleRule, Triangle, find_triangles
from .robust import (
    MAD_SCALE,
    classical_zscores,
    hampel_filter,
    mad,
    median,
    robust_zscores,
    rolling_classical_z,
    rolling_robust_z,
)
from .rules import (
    CloseOutsideQuote,
    CrossedQuote,
    LateMark,
    MissingDays,
    NonPositivePrice,
    NonTradingDayPrint,
    RobustOutlier,
    Rule,
    SpikeReversal,
    StaleMark,
    UnexplainedJump,
    WideSpread,
    default_rules,
    rule_catalogue,
)

__all__ = [
    "DIMENSION_WEIGHTS",
    "EXPECTED_RULES",
    "MAD_SCALE",
    "CloseOutsideQuote",
    "CrossedQuote",
    "DetectionScore",
    "Dimension",
    "Finding",
    "FxInverseRule",
    "FxTriangleRule",
    "KindScore",
    "LateMark",
    "MissingDays",
    "NonPositivePrice",
    "NonTradingDayPrint",
    "QualityEngine",
    "QualityReport",
    "RobustOutlier",
    "Rule",
    "RuleScore",
    "SeriesContext",
    "SeriesScore",
    "Severity",
    "SpikeReversal",
    "StaleMark",
    "Triangle",
    "UnexplainedJump",
    "WideSpread",
    "classical_zscores",
    "default_rules",
    "evaluate",
    "find_triangles",
    "fx_series_rules",
    "hampel_filter",
    "mad",
    "median",
    "robust_zscores",
    "rolling_classical_z",
    "rolling_robust_z",
    "rule_catalogue",
    "run_quality",
    "series_report",
]
