"""Portfolio accounting: the journal, realised lots, daily valuations, reconciliation breaks.

``journal_entries`` and ``journal_postings`` hold the double-entry book of
record (ADR 0014); a posting carries its local and base-currency amounts, and
the trial balance is one GROUP BY over it. ``realised_lots`` is the unit every
tax report is built from. ``portfolio_valuations`` and ``position_valuations``
store the daily mark-to-market, and ``reconciliation_breaks`` each statement
date's differences with the custodian and their causes.

``tax_lots`` gains the three tax attributes of a lot - the tacked holding
period start, the opening FX rate and the wash sale adjustment. Existing rows
take the neutral values (rate 1, no adjustment) through server defaults, so
the migration runs on a populated database.

Revision ID: 0003
Revises: 0002
Create Date: 2026-09-24
"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = "0003"
down_revision: str | None = "0002"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "journal_entries",
        sa.Column("entry_id", sa.String(length=96), nullable=False),
        sa.Column("portfolio_id", sa.String(length=64), nullable=False),
        sa.Column("effective_date", sa.Date(), nullable=False),
        sa.Column("kind", sa.String(length=24), nullable=False),
        sa.Column("description", sa.String(length=256), nullable=False),
        sa.Column("source_id", sa.String(length=96), nullable=True),
        sa.Column("reverses", sa.String(length=96), nullable=True),
        sa.Column("cross_currency", sa.Boolean(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["portfolio_id"], ["portfolios.portfolio_id"], name=op.f("fk_journal_entries_portfolio_id_portfolios")
        ),
        sa.PrimaryKeyConstraint("entry_id", name=op.f("pk_journal_entries")),
    )
    with op.batch_alter_table("journal_entries", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_journal_entries_effective_date"), ["effective_date"], unique=False)
        batch_op.create_index(batch_op.f("ix_journal_entries_kind"), ["kind"], unique=False)
        batch_op.create_index("ix_journal_entries_portfolio_date", ["portfolio_id", "effective_date"], unique=False)
        batch_op.create_index(batch_op.f("ix_journal_entries_portfolio_id"), ["portfolio_id"], unique=False)
        batch_op.create_index(batch_op.f("ix_journal_entries_source_id"), ["source_id"], unique=False)

    op.create_table(
        "portfolio_valuations",
        sa.Column("portfolio_id", sa.String(length=64), nullable=False),
        sa.Column("valuation_date", sa.Date(), nullable=False),
        sa.Column("base_currency", sa.String(length=3), nullable=False),
        sa.Column("nav", sa.Numeric(precision=28, scale=10), nullable=False),
        sa.Column("securities", sa.Numeric(precision=28, scale=10), nullable=False),
        sa.Column("accrued_interest", sa.Numeric(precision=28, scale=10), nullable=False),
        sa.Column("cash_like", sa.Numeric(precision=28, scale=10), nullable=False),
        sa.Column("settled_cash", sa.Numeric(precision=28, scale=10), nullable=False),
        sa.Column("receivables", sa.Numeric(precision=28, scale=10), nullable=False),
        sa.Column("payables", sa.Numeric(precision=28, scale=10), nullable=False),
        sa.Column("cost_base", sa.Numeric(precision=28, scale=10), nullable=False),
        sa.Column("unrealised_price", sa.Numeric(precision=28, scale=10), nullable=False),
        sa.Column("unrealised_fx", sa.Numeric(precision=28, scale=10), nullable=False),
        sa.Column("missing_prices", sa.Integer(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["portfolio_id"], ["portfolios.portfolio_id"], name=op.f("fk_portfolio_valuations_portfolio_id_portfolios")
        ),
        sa.PrimaryKeyConstraint("portfolio_id", "valuation_date", name=op.f("pk_portfolio_valuations")),
    )
    op.create_table(
        "position_valuations",
        sa.Column("portfolio_id", sa.String(length=64), nullable=False),
        sa.Column("valuation_date", sa.Date(), nullable=False),
        sa.Column("instrument_id", sa.String(length=64), nullable=False),
        sa.Column("currency", sa.String(length=3), nullable=False),
        sa.Column("quantity", sa.Numeric(precision=28, scale=10), nullable=False),
        sa.Column("price", sa.Numeric(precision=28, scale=10), nullable=False),
        sa.Column("price_date", sa.Date(), nullable=False),
        sa.Column("fx_rate", sa.Numeric(precision=20, scale=12), nullable=False),
        sa.Column("market_value", sa.Numeric(precision=28, scale=10), nullable=False),
        sa.Column("market_value_base", sa.Numeric(precision=28, scale=10), nullable=False),
        sa.Column("accrued_base", sa.Numeric(precision=28, scale=10), nullable=False),
        sa.Column("cost_base", sa.Numeric(precision=28, scale=10), nullable=False),
        sa.Column("unrealised_price_base", sa.Numeric(precision=28, scale=10), nullable=False),
        sa.Column("unrealised_fx_base", sa.Numeric(precision=28, scale=10), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["portfolio_id"], ["portfolios.portfolio_id"], name=op.f("fk_position_valuations_portfolio_id_portfolios")
        ),
        sa.PrimaryKeyConstraint("portfolio_id", "valuation_date", "instrument_id", name=op.f("pk_position_valuations")),
    )
    op.create_table(
        "realised_lots",
        sa.Column("portfolio_id", sa.String(length=64), nullable=False),
        sa.Column("disposal_id", sa.String(length=96), nullable=False),
        sa.Column("lot_id", sa.String(length=96), nullable=False),
        sa.Column("instrument_id", sa.String(length=64), nullable=False),
        sa.Column("open_date", sa.Date(), nullable=False),
        sa.Column("holding_start", sa.Date(), nullable=False),
        sa.Column("close_date", sa.Date(), nullable=False),
        sa.Column("quantity", sa.Numeric(precision=28, scale=10), nullable=False),
        sa.Column("currency", sa.String(length=3), nullable=False),
        sa.Column("proceeds", sa.Numeric(precision=28, scale=10), nullable=False),
        sa.Column("cost", sa.Numeric(precision=28, scale=10), nullable=False),
        sa.Column("open_fx_rate", sa.Numeric(precision=20, scale=12), nullable=False),
        sa.Column("close_fx_rate", sa.Numeric(precision=20, scale=12), nullable=False),
        sa.Column("wash_sale_basis", sa.Numeric(precision=28, scale=10), nullable=False),
        sa.Column("disallowed_loss", sa.Numeric(precision=28, scale=10), nullable=False),
        sa.Column("kind", sa.String(length=16), nullable=False),
        sa.Column("term", sa.String(length=8), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["portfolio_id"], ["portfolios.portfolio_id"], name=op.f("fk_realised_lots_portfolio_id_portfolios")
        ),
        sa.PrimaryKeyConstraint("portfolio_id", "disposal_id", "lot_id", name=op.f("pk_realised_lots")),
    )
    with op.batch_alter_table("realised_lots", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_realised_lots_close_date"), ["close_date"], unique=False)
        batch_op.create_index(batch_op.f("ix_realised_lots_instrument_id"), ["instrument_id"], unique=False)
        batch_op.create_index(batch_op.f("ix_realised_lots_term"), ["term"], unique=False)

    op.create_table(
        "reconciliation_breaks",
        sa.Column("portfolio_id", sa.String(length=64), nullable=False),
        sa.Column("as_of", sa.Date(), nullable=False),
        sa.Column("kind", sa.String(length=24), nullable=False),
        sa.Column("break_key", sa.String(length=64), nullable=False),
        sa.Column("cause", sa.String(length=24), nullable=False),
        sa.Column("causes", sa.String(length=96), nullable=False),
        sa.Column("currency", sa.String(length=3), nullable=False),
        sa.Column("book_value", sa.Numeric(precision=28, scale=10), nullable=False),
        sa.Column("custodian_value", sa.Numeric(precision=28, scale=10), nullable=False),
        sa.Column("value_base", sa.Numeric(precision=28, scale=10), nullable=False),
        sa.Column("explanation", sa.String(length=256), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["portfolio_id"], ["portfolios.portfolio_id"], name=op.f("fk_reconciliation_breaks_portfolio_id_portfolios")
        ),
        sa.PrimaryKeyConstraint("portfolio_id", "as_of", "kind", "break_key", name=op.f("pk_reconciliation_breaks")),
    )
    with op.batch_alter_table("reconciliation_breaks", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_reconciliation_breaks_cause"), ["cause"], unique=False)

    op.create_table(
        "journal_postings",
        sa.Column("entry_id", sa.String(length=96), nullable=False),
        sa.Column("line_no", sa.Integer(), nullable=False),
        sa.Column("account_code", sa.String(length=4), nullable=False),
        sa.Column("currency", sa.String(length=3), nullable=False),
        sa.Column("amount", sa.Numeric(precision=28, scale=10), nullable=False),
        sa.Column("base_amount", sa.Numeric(precision=28, scale=10), nullable=False),
        sa.Column("instrument_id", sa.String(length=64), nullable=True),
        sa.Column("memo", sa.String(length=128), nullable=True),
        sa.ForeignKeyConstraint(
            ["entry_id"],
            ["journal_entries.entry_id"],
            name=op.f("fk_journal_postings_entry_id_journal_entries"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("entry_id", "line_no", name=op.f("pk_journal_postings")),
    )
    with op.batch_alter_table("journal_postings", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_journal_postings_account_code"), ["account_code"], unique=False)
        batch_op.create_index(batch_op.f("ix_journal_postings_instrument_id"), ["instrument_id"], unique=False)

    with op.batch_alter_table("tax_lots", schema=None) as batch_op:
        batch_op.add_column(sa.Column("holding_period_start", sa.Date(), nullable=True))
        batch_op.add_column(
            sa.Column("open_fx_rate", sa.Numeric(precision=20, scale=12), server_default="1", nullable=False)
        )
        batch_op.add_column(
            sa.Column("wash_sale_adjustment", sa.Numeric(precision=28, scale=10), server_default="0", nullable=False)
        )

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("tax_lots", schema=None) as batch_op:
        batch_op.drop_column("wash_sale_adjustment")
        batch_op.drop_column("open_fx_rate")
        batch_op.drop_column("holding_period_start")

    with op.batch_alter_table("journal_postings", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_journal_postings_instrument_id"))
        batch_op.drop_index(batch_op.f("ix_journal_postings_account_code"))

    op.drop_table("journal_postings")
    with op.batch_alter_table("reconciliation_breaks", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_reconciliation_breaks_cause"))

    op.drop_table("reconciliation_breaks")
    with op.batch_alter_table("realised_lots", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_realised_lots_term"))
        batch_op.drop_index(batch_op.f("ix_realised_lots_instrument_id"))
        batch_op.drop_index(batch_op.f("ix_realised_lots_close_date"))

    op.drop_table("realised_lots")
    op.drop_table("position_valuations")
    op.drop_table("portfolio_valuations")
    with op.batch_alter_table("journal_entries", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_journal_entries_source_id"))
        batch_op.drop_index(batch_op.f("ix_journal_entries_portfolio_id"))
        batch_op.drop_index("ix_journal_entries_portfolio_date")
        batch_op.drop_index(batch_op.f("ix_journal_entries_kind"))
        batch_op.drop_index(batch_op.f("ix_journal_entries_effective_date"))

    op.drop_table("journal_entries")
    # ### end Alembic commands ###
