"""The migrations must produce exactly the schema the ORM expects.

A platform that keeps client books of record cannot tolerate the schema and the
code drifting apart, so ``alembic check`` is asserted here as well as in CI.
"""

from __future__ import annotations

from pathlib import Path

import pytest
from alembic import command
from alembic.config import Config
from alembic.util.exc import AutogenerateDiffsDetected
from sqlalchemy import create_engine, inspect

from meridian.config import get_settings, reset_settings_cache

PROJECT_ROOT = Path(__file__).resolve().parents[2]
ALEMBIC_INI = PROJECT_ROOT / "alembic.ini"

EXPECTED_TABLES = {
    "accounts",
    "benchmarks",
    "clients",
    "fx_rates",
    "households",
    "instruments",
    "portfolios",
    "prices",
    "tax_lots",
    "transactions",
}


@pytest.fixture
def alembic_config(tmp_path, monkeypatch):
    database = tmp_path / "migrations.sqlite"
    monkeypatch.setenv("MERIDIAN_DATABASE_URL", f"sqlite:///{database.as_posix()}")
    reset_settings_cache()
    config = Config(str(ALEMBIC_INI))
    config.set_main_option("script_location", str(PROJECT_ROOT / "alembic"))
    yield config
    reset_settings_cache()


def _table_names() -> set[str]:
    engine = create_engine(get_settings().database_url)
    try:
        return set(inspect(engine).get_table_names())
    finally:
        engine.dispose()


def test_upgrade_creates_every_table(alembic_config: Config):
    command.upgrade(alembic_config, "head")
    tables = _table_names()
    assert tables >= EXPECTED_TABLES
    assert "alembic_version" in tables


def test_migrated_schema_matches_the_orm_metadata(alembic_config: Config):
    command.upgrade(alembic_config, "head")
    try:
        command.check(alembic_config)
    except AutogenerateDiffsDetected as exc:  # pragma: no cover - only fires on real drift
        pytest.fail(f"models and migrations have drifted apart: {exc}")


def test_downgrade_removes_the_schema(alembic_config: Config):
    command.upgrade(alembic_config, "head")
    command.downgrade(alembic_config, "base")
    assert not EXPECTED_TABLES & _table_names()


def test_upgrade_is_repeatable_after_a_full_downgrade(alembic_config: Config):
    command.upgrade(alembic_config, "head")
    command.downgrade(alembic_config, "base")
    command.upgrade(alembic_config, "head")
    assert _table_names() >= EXPECTED_TABLES
