"""The migrations must produce exactly the schema the ORM expects.

A platform that keeps client books of record cannot tolerate the schema and the
code drifting apart, so ``alembic check`` is asserted here as well as in CI.
"""

from __future__ import annotations

from pathlib import Path

import pytest
from alembic import command
from alembic.config import Config
from alembic.util.exc import AutogenerateDiffsDetected
from sqlalchemy import create_engine, inspect, text

from meridian.config import get_settings, reset_settings_cache

PROJECT_ROOT = Path(__file__).resolve().parents[2]
ALEMBIC_INI = PROJECT_ROOT / "alembic.ini"

EXPECTED_TABLES = {
    "accounts",
    "attribution_effects",
    "benchmarks",
    "compliance_breaches",
    "compliance_results",
    "compliance_rules",
    "clients",
    "corporate_actions",
    "fx_rates",
    "households",
    "identifier_xref",
    "instruments",
    "journal_entries",
    "journal_postings",
    "performance_returns",
    "risk_exposures",
    "risk_factor_returns",
    "risk_forecasts",
    "portfolio_valuations",
    "portfolios",
    "pretrade_checks",
    "position_valuations",
    "price_observations",
    "prices",
    "quality_findings",
    "quality_runs",
    "realised_lots",
    "reconciliation_breaks",
    "tax_lots",
    "transactions",
}


@pytest.fixture
def alembic_config(tmp_path, monkeypatch):
    database = tmp_path / "migrations.sqlite"
    monkeypatch.setenv("MERIDIAN_DATABASE_URL", f"sqlite:///{database.as_posix()}")
    reset_settings_cache()
    config = Config(str(ALEMBIC_INI))
    config.set_main_option("script_location", str(PROJECT_ROOT / "alembic"))
    yield config
    reset_settings_cache()


def _table_names() -> set[str]:
    engine = create_engine(get_settings().database_url)
    try:
        return set(inspect(engine).get_table_names())
    finally:
        engine.dispose()


def test_upgrade_creates_every_table(alembic_config: Config):
    command.upgrade(alembic_config, "head")
    tables = _table_names()
    assert tables >= EXPECTED_TABLES
    assert "alembic_version" in tables


def test_migrated_schema_matches_the_orm_metadata(alembic_config: Config):
    command.upgrade(alembic_config, "head")
    try:
        command.check(alembic_config)
    except AutogenerateDiffsDetected as exc:  # pragma: no cover - only fires on real drift
        pytest.fail(f"models and migrations have drifted apart: {exc}")


def test_downgrade_removes_the_schema(alembic_config: Config):
    command.upgrade(alembic_config, "head")
    command.downgrade(alembic_config, "base")
    assert not EXPECTED_TABLES & _table_names()


def test_upgrade_is_repeatable_after_a_full_downgrade(alembic_config: Config):
    command.upgrade(alembic_config, "head")
    command.downgrade(alembic_config, "base")
    command.upgrade(alembic_config, "head")
    assert _table_names() >= EXPECTED_TABLES


def test_migration_0003_upgrades_a_populated_tax_lot_table(alembic_config: Config):
    """Existing lots take the neutral tax attributes: rate 1, no wash sale adjustment, no tacking."""
    command.upgrade(alembic_config, "0002")
    engine = create_engine(get_settings().database_url)
    try:
        with engine.begin() as connection:
            connection.execute(
                text(
                    "INSERT INTO instruments (instrument_id, name, instrument_type, asset_class, currency, calendar,"
                    " status, multiplier, created_at, updated_at) VALUES ('X', 'X', 'common_stock', 'equity', 'USD',"
                    " 'XNYS', 'active', 1, '2026-01-02', '2026-01-02')"
                )
            )
            connection.execute(
                text(
                    "INSERT INTO portfolios (portfolio_id, name, base_currency, created_at, updated_at)"
                    " VALUES ('P', 'P', 'USD', '2026-01-02', '2026-01-02')"
                )
            )
            connection.execute(
                text(
                    "INSERT INTO tax_lots (lot_id, portfolio_id, instrument_id, open_date, quantity, cost_per_unit,"
                    " currency, created_at, updated_at) VALUES ('L1', 'P', 'X', '2025-01-02', 10, 5, 'USD',"
                    " '2026-01-02', '2026-01-02')"
                )
            )
        command.upgrade(alembic_config, "head")
        with engine.connect() as connection:
            row = connection.execute(
                text("SELECT open_fx_rate, wash_sale_adjustment, holding_period_start FROM tax_lots")
            ).one()
        assert float(row[0]) == 1.0 and float(row[1]) == 0.0 and row[2] is None
    finally:
        engine.dispose()
